name: Update @axe-core/watcher

on:
  workflow_dispatch:
  schedule:
    # Scheduled to run at 2am every day
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd example && npm install --save-dev @axe-core/watcher@latest
      - name: Open PR
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # tag=v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore: Update @axe-core/watcher"
          branch: auto-update-watcher
          base: main
          title: "chore: Update @axe-core/watcher"
          body: |
            This patch updates version of [`@axe-core/watcher`](https://npmjs.org/@axe-core/watcher) to the latest version.
            This PR was opened by a robot :robot: :tada:.
